### ISSUE TITLE
这个问题是什么原因呢

### ISSUE THREAD

**Issue by nidebenmao** [chenhsuanlin/inverse-compositional-STN#19]
您好，我在训练您的tensorflowsh书写数字时候，遇见了这个问题，请问是什么原因呢

Traceback (most recent call last):
  File "F:/stn1/inverse-compositional-STN-master/MNIST-tensorflow/train.py", line 74, in <module>
    traintrainData,validData,testData = data.loadMNIST("F:/stn1/inverse-compositional-STN-master/MNIST-tenso
rflow/data/MNIST.npz")
  File "F:\stn1\inverse-compositional-STN-master\MNIST-tensorflow\data.py", line 25, in loadMNIST
    trainData = MNIST["train"].item()
  File "D:\python3\lib\site-packages\numpy\lib\npyio.py", line 262, in __getitem__
    raise KeyError("%s is not a file in the archive" % key)
KeyError: 'train is not a file in the archive'

**Comment by chenhsuanlin** [comment]
I've never seen this problem -- did this happen when you first downloaded MNIST with Tensorflow? It's probably useful to look at what's stored inside the variable `MNIST`.
